name: swiper_mobile
publish_to: 'none'
version: 1.0.0+1
environment:
 sdk: '>=3.1.2 <4.0.0'
isar_version: &isar_version 3.1.0
dependencies:
 flutter:
  sdk: flutter
 #Localization
 flutter_localizations:
  sdk: flutter
 #Icons
 cupertino_icons: ^1.0.6
 #code generation
 freezed_annotation: ^2.4.1
 json_annotation: ^4.8.1
 #RESTful API
 dio: ^5.3.3
 #State Management
 flutter_bloc: ^8.1.3
 #Network Connectivity
 connectivity_plus: ^4.0.2
 #Dependency Injection
 injectable: ^2.3.0
 get_it: ^7.6.4
 #Value Equality
 equatable: ^2.0.5
 #Functioanl Programming
 fpdart: ^1.1.0
 #Dart Extensions
 dartx: ^1.2.0
 #Navigation
 go_router: ^11.1.2
 #Local Storage
 isar: *isar_version
 isar_flutter_libs: *isar_version
 #Secure Storage
 flutter_secure_storage: ^9.0.0
 #Responsive
 flutter_screenutil: ^5.9.0
dev_dependencies:
 flutter_test:
  sdk: flutter
 isar_generator: *isar_version
 flutter_lints: ^2.0.3
 build_runner: ^2.4.6
 freezed: 
 json_serializable: ^6.7.1
 injectable_generator: ^2.4.0

flutter:
 assets:
  - assets/images/
 uses-material-design: true
flutter_intl:
 arb_dir: assets/l10n
 class_name: AppLocalizations
 enabled: true
 main_locale: en
 output_dir: lib/src/I10n/generated
 nullable-getter: false